### ISSUE TITLE
Insecure URL used in bootstrap framework file needs to be secure URL

### ISSUE THREAD

**Issue by wpdev10** [AyeCode/wp-ayecode-ui#4]
URL: http://www.w3.org/2000/svg in files ayecode-ui-compatibility.css

Ticket: https://userswp.io/support/topic/no-padlock-ssl-certificate-issue/

**Comment by Stiofan** [comment]
This is a false positive, for SVG the spec states it must be http.  The user seems to have found and fixed their issue
