### ISSUE TITLE
Throws JS error if settings changed to prevent conflicts

### ISSUE THREAD

**Issue by wpdev10** [AyeCode/wp-ayecode-ui#5]
In edit place category upload button not working due to JS error when Load JS setting is set to required functions only for preventing bootstrap conflicts on the frontend.

https://github.com/AyeCode/wp-ayecode-ui/blob/f4a7dd4baacbada3a6fb186902c8514868239821/includes/ayecode-ui-settings.php#L388
This throws .popper function not defined.

**Comment by Stiofan** [comment]
fixed by splitting front/backend settings.
